eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
message: Hello from Config Server
gateway:
  url: http://localhost:8084

security:
  role-rules:
    - path: /products/admin/**
      roles: USER

    - path: /products/**
      roles: USER,ADMIN

    - path: /orders/**
      roles: USER,ADMIN
